-- Step 38: customer API credential lifecycle.
-- Raw API keys are generated by the serverless API and are never stored in Postgres.
-- Only SHA-256 hex digests and non-secret prefixes are persisted.

create table public.dpp_api_credentials (
  id uuid primary key default gen_random_uuid(),
  organization_id uuid not null references public.dpp_organizations(id) on delete cascade,
  name text not null check (length(btrim(name)) between 1 and 160),
  key_prefix text not null check (key_prefix ~ '^sf_dpp_[0-9a-f]{10}$'),
  secret_hash text not null check (secret_hash ~ '^[0-9a-f]{64}$'),
  scopes text[] not null check (
    cardinality(scopes) between 1 and 6
    and scopes <@ array[
      'passports:read',
      'passports:write',
      'imports:write',
      'exports:read',
      'carriers:write',
      'webhooks:manage'
    ]::text[]
  ),
  status text not null default 'active' check (status in ('active','revoked')),
  expires_at timestamptz null,
  last_used_at timestamptz null,
  created_by uuid null references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  revoked_at timestamptz null,
  revoked_by uuid null references auth.users(id) on delete set null,
  revoke_reason text null check (revoke_reason is null or length(revoke_reason) <= 500),
  unique (secret_hash),
  unique (organization_id,key_prefix)
);

create index dpp_api_credentials_org_status_idx
  on public.dpp_api_credentials(organization_id,status,created_at desc);

alter table public.dpp_api_credentials enable row level security;
revoke all on table public.dpp_api_credentials from anon,authenticated;

create or replace function public.dpp_api_credentials_list()
returns jsonb
language plpgsql
stable
security definer
set search_path=public,pg_temp
as $fn$
declare
  v_org uuid;
  v_rows jsonb;
begin
  v_org:=public.dpp_require_active_role(array['owner','admin']);

  select coalesce(
    jsonb_agg(
      jsonb_build_object(
        'id',c.id,
        'name',c.name,
        'key_prefix',c.key_prefix,
        'scopes',to_jsonb(c.scopes),
        'status',c.status,
        'expires_at',c.expires_at,
        'last_used_at',c.last_used_at,
        'created_at',c.created_at,
        'revoked_at',c.revoked_at,
        'revoke_reason',c.revoke_reason
      )
      order by c.created_at desc
    ),
    '[]'::jsonb
  )
  into v_rows
  from public.dpp_api_credentials c
  where c.organization_id=v_org;

  return v_rows;
end
$fn$;

create or replace function public.dpp_api_credential_create(
  p_name text,
  p_key_prefix text,
  p_secret_hash text,
  p_scopes text[],
  p_expires_at timestamptz default null
)
returns jsonb
language plpgsql
security definer
set search_path=public,pg_temp
as $fn$
declare
  v_org uuid;
  v_user uuid;
  v_row public.dpp_api_credentials%rowtype;
begin
  v_org:=public.dpp_require_active_role(array['owner','admin']);
  v_user:=public.dpp_request_user_id();

  if length(btrim(coalesce(p_name,''))) not between 1 and 160
     or p_key_prefix !~ '^sf_dpp_[0-9a-f]{10}$'
     or p_secret_hash !~ '^[0-9a-f]{64}$'
     or p_scopes is null
     or cardinality(p_scopes) not between 1 and 6
     or not (p_scopes <@ array[
       'passports:read','passports:write','imports:write',
       'exports:read','carriers:write','webhooks:manage'
     ]::text[])
     or cardinality(p_scopes) <> cardinality(array(select distinct unnest(p_scopes)))
     or (p_expires_at is not null and p_expires_at <= now())
  then
    raise exception 'invalid API credential payload' using errcode='DP202';
  end if;

  insert into public.dpp_api_credentials(
    organization_id,name,key_prefix,secret_hash,scopes,expires_at,created_by
  ) values (
    v_org,btrim(p_name),p_key_prefix,p_secret_hash,p_scopes,p_expires_at,v_user
  )
  returning * into v_row;

  return jsonb_build_object(
    'id',v_row.id,
    'name',v_row.name,
    'key_prefix',v_row.key_prefix,
    'scopes',to_jsonb(v_row.scopes),
    'status',v_row.status,
    'expires_at',v_row.expires_at,
    'last_used_at',v_row.last_used_at,
    'created_at',v_row.created_at,
    'revoked_at',v_row.revoked_at,
    'revoke_reason',v_row.revoke_reason
  );
end
$fn$;

create or replace function public.dpp_api_credential_revoke(
  p_id uuid,
  p_reason text default 'manual revoke'
)
returns jsonb
language plpgsql
security definer
set search_path=public,pg_temp
as $fn$
declare
  v_org uuid;
  v_user uuid;
  v_row public.dpp_api_credentials%rowtype;
  v_reason text;
begin
  v_org:=public.dpp_require_active_role(array['owner','admin']);
  v_user:=public.dpp_request_user_id();
  v_reason:=btrim(coalesce(p_reason,'manual revoke'));

  if length(v_reason) not between 1 and 500 then
    raise exception 'invalid revoke reason' using errcode='DP202';
  end if;

  update public.dpp_api_credentials
  set status='revoked',
      revoked_at=coalesce(revoked_at,now()),
      revoked_by=coalesce(revoked_by,v_user),
      revoke_reason=coalesce(revoke_reason,v_reason)
  where id=p_id and organization_id=v_org
  returning * into v_row;

  if not found then
    raise exception 'API credential not found' using errcode='DP201';
  end if;

  return jsonb_build_object(
    'id',v_row.id,
    'name',v_row.name,
    'key_prefix',v_row.key_prefix,
    'scopes',to_jsonb(v_row.scopes),
    'status',v_row.status,
    'expires_at',v_row.expires_at,
    'last_used_at',v_row.last_used_at,
    'created_at',v_row.created_at,
    'revoked_at',v_row.revoked_at,
    'revoke_reason',v_row.revoke_reason
  );
end
$fn$;

create or replace function public.dpp_api_credential_rotate(
  p_id uuid,
  p_key_prefix text,
  p_secret_hash text
)
returns jsonb
language plpgsql
security definer
set search_path=public,pg_temp
as $fn$
declare
  v_org uuid;
  v_user uuid;
  v_old public.dpp_api_credentials%rowtype;
  v_new public.dpp_api_credentials%rowtype;
begin
  v_org:=public.dpp_require_active_role(array['owner','admin']);
  v_user:=public.dpp_request_user_id();

  if p_key_prefix !~ '^sf_dpp_[0-9a-f]{10}$'
     or p_secret_hash !~ '^[0-9a-f]{64}$' then
    raise exception 'invalid API credential payload' using errcode='DP202';
  end if;

  select *
  into v_old
  from public.dpp_api_credentials
  where id=p_id and organization_id=v_org
  for update;

  if not found then
    raise exception 'API credential not found' using errcode='DP201';
  end if;

  if v_old.status<>'active' then
    raise exception 'only active credentials can be rotated' using errcode='DP202';
  end if;

  if v_old.expires_at is not null and v_old.expires_at<=now() then
    raise exception 'expired credentials cannot be rotated' using errcode='DP202';
  end if;

  update public.dpp_api_credentials
  set status='revoked',
      revoked_at=now(),
      revoked_by=v_user,
      revoke_reason='rotated'
  where id=v_old.id;

  insert into public.dpp_api_credentials(
    organization_id,name,key_prefix,secret_hash,scopes,expires_at,created_by
  ) values (
    v_org,v_old.name,p_key_prefix,p_secret_hash,v_old.scopes,v_old.expires_at,v_user
  )
  returning * into v_new;

  return jsonb_build_object(
    'id',v_new.id,
    'name',v_new.name,
    'key_prefix',v_new.key_prefix,
    'scopes',to_jsonb(v_new.scopes),
    'status',v_new.status,
    'expires_at',v_new.expires_at,
    'last_used_at',v_new.last_used_at,
    'created_at',v_new.created_at,
    'revoked_at',v_new.revoked_at,
    'revoke_reason',v_new.revoke_reason,
    'rotated_from',v_old.id
  );
end
$fn$;

create or replace function public.dpp_service_api_credential_authenticate(
  p_secret_hash text
)
returns jsonb
language plpgsql
security definer
set search_path=public,pg_temp
as $fn$
declare
  v_row public.dpp_api_credentials%rowtype;
begin
  if p_secret_hash !~ '^[0-9a-f]{64}$' then
    return null;
  end if;

  select *
  into v_row
  from public.dpp_api_credentials
  where secret_hash=p_secret_hash
    and status='active'
    and (expires_at is null or expires_at>now())
  limit 1;

  if not found then
    return null;
  end if;

  update public.dpp_api_credentials
  set last_used_at=now()
  where id=v_row.id;

  return jsonb_build_object(
    'credential_id',v_row.id,
    'organization_id',v_row.organization_id,
    'key_prefix',v_row.key_prefix,
    'scopes',to_jsonb(v_row.scopes)
  );
end
$fn$;

revoke all on function public.dpp_api_credentials_list() from public,anon;
revoke all on function public.dpp_api_credential_create(text,text,text,text[],timestamptz) from public,anon;
revoke all on function public.dpp_api_credential_revoke(uuid,text) from public,anon;
revoke all on function public.dpp_api_credential_rotate(uuid,text,text) from public,anon;
revoke all on function public.dpp_service_api_credential_authenticate(text) from public,anon,authenticated;

grant execute on function public.dpp_api_credentials_list() to authenticated;
grant execute on function public.dpp_api_credential_create(text,text,text,text[],timestamptz) to authenticated;
grant execute on function public.dpp_api_credential_revoke(uuid,text) to authenticated;
grant execute on function public.dpp_api_credential_rotate(uuid,text,text) to authenticated;
grant execute on function public.dpp_service_api_credential_authenticate(text) to service_role;

comment on table public.dpp_api_credentials is
  'Step 38: tenant-scoped customer API credentials. Stores only hashes/prefixes; raw keys are never persisted.';
comment on function public.dpp_service_api_credential_authenticate(text) is
  'Service-role-only API key resolver for future customer API authentication.';
