-- BAT52 Supplier portal invitation/acceptance API.
-- Raw invitation tokens are generated by the HTTP layer and never persisted.
-- Database stores only SHA-256 token digests.

create or replace function public.dpp_api_supplier_invitation_create(
  p_supplier_id uuid,
  p_invitee_email text,
  p_requested_role text,
  p_token_sha256 text,
  p_expires_at timestamptz
)
returns jsonb
language plpgsql
security definer
set search_path=public,pg_temp
as $fn$
declare
  v_org uuid;
  v_user uuid;
  v_row public.dpp_supplier_invitations%rowtype;
begin
  v_org:=public.dpp_require_active_role(array['owner','admin']);
  v_user:=public.dpp_request_user_id();

  if p_supplier_id is null or not exists(
    select 1 from public.dpp_suppliers s
    where s.organization_id=v_org and s.id=p_supplier_id
  ) then
    raise exception 'supplier not found' using errcode='DP601';
  end if;

  if p_invitee_email is null
     or length(btrim(p_invitee_email)) not between 3 and 320
     or lower(btrim(p_invitee_email)) !~ '^[^[:space:]@]+@[^[:space:]@]+\.[^[:space:]@]+$' then
    raise exception 'invalid invitation email' using errcode='DP602';
  end if;

  if p_requested_role is null
     or p_requested_role not in ('supplier_editor','supplier_viewer') then
    raise exception 'invalid supplier portal role' using errcode='DP602';
  end if;

  if p_token_sha256 is null or p_token_sha256 !~ '^[0-9a-f]{64}$' then
    raise exception 'invalid invitation token digest' using errcode='DP602';
  end if;

  if p_expires_at is null
     or p_expires_at <= now() + interval '5 minutes'
     or p_expires_at > now() + interval '30 days' then
    raise exception 'invalid invitation expiry' using errcode='DP602';
  end if;

  -- Revoke older pending invitations for the same supplier/email so only the
  -- latest issued invitation remains usable.
  update public.dpp_supplier_invitations
  set status='revoked'
  where organization_id=v_org
    and supplier_id=p_supplier_id
    and invitee_email=lower(btrim(p_invitee_email))
    and status='pending';

  insert into public.dpp_supplier_invitations(
    organization_id,supplier_id,invitee_email,requested_role,token_sha256,
    status,expires_at,created_by
  ) values(
    v_org,p_supplier_id,lower(btrim(p_invitee_email)),p_requested_role,p_token_sha256,
    'pending',p_expires_at,v_user
  )
  returning * into v_row;

  return jsonb_build_object(
    'id',v_row.id,
    'supplier_id',v_row.supplier_id,
    'invitee_email',v_row.invitee_email,
    'requested_role',v_row.requested_role,
    'status',v_row.status,
    'expires_at',v_row.expires_at,
    'created_at',v_row.created_at
  );
end
$fn$;

create or replace function public.dpp_api_supplier_invitation_accept(
  p_token_sha256 text
)
returns jsonb
language plpgsql
security definer
set search_path=public,pg_temp
as $fn$
declare
  v_user uuid;
  v_inv public.dpp_supplier_invitations%rowtype;
begin
  v_user:=public.dpp_request_user_id();
  if v_user is null then
    raise exception 'authenticated user context is required' using errcode='DP101';
  end if;

  if p_token_sha256 is null or p_token_sha256 !~ '^[0-9a-f]{64}$' then
    raise exception 'invalid supplier invitation' using errcode='DP605';
  end if;

  select *
  into v_inv
  from public.dpp_supplier_invitations i
  where i.token_sha256=p_token_sha256
    and i.status='pending'
  for update;

  if not found or v_inv.expires_at <= now() then
    raise exception 'supplier invitation is invalid or expired' using errcode='DP605';
  end if;

  update public.dpp_supplier_invitations
  set status='accepted',
      accepted_by=v_user,
      accepted_at=now()
  where id=v_inv.id
    and status='pending';

  insert into public.dpp_supplier_portal_members(
    organization_id,supplier_id,user_id,role,status,created_by
  ) values(
    v_inv.organization_id,v_inv.supplier_id,v_user,v_inv.requested_role,'active',v_inv.created_by
  )
  on conflict(organization_id,supplier_id,user_id) do update
  set role=excluded.role,
      status='active';

  return jsonb_build_object(
    'invitation_id',v_inv.id,
    'organization_id',v_inv.organization_id,
    'supplier_id',v_inv.supplier_id,
    'role',v_inv.requested_role,
    'status','accepted',
    'accepted_by',v_user
  );
end
$fn$;

create or replace function public.dpp_api_supplier_invitations_list(
  p_supplier_id uuid default null
)
returns jsonb
language plpgsql
stable
security definer
set search_path=public,pg_temp
as $fn$
declare
  v_org uuid;
  v_result jsonb;
begin
  v_org:=public.dpp_require_active_role(array['owner','admin','editor','viewer']);

  select coalesce(
    jsonb_agg(
      jsonb_build_object(
        'id',i.id,
        'supplier_id',i.supplier_id,
        'invitee_email',i.invitee_email,
        'requested_role',i.requested_role,
        'status',case
          when i.status='pending' and i.expires_at<=now() then 'expired'
          else i.status
        end,
        'expires_at',i.expires_at,
        'accepted_at',i.accepted_at,
        'created_at',i.created_at
      )
      order by i.created_at desc,i.id desc
    ),
    '[]'::jsonb
  )
  into v_result
  from public.dpp_supplier_invitations i
  where i.organization_id=v_org
    and (p_supplier_id is null or i.supplier_id=p_supplier_id);

  return v_result;
end
$fn$;

revoke all on function public.dpp_api_supplier_invitation_create(uuid,text,text,text,timestamptz) from public,anon;
revoke all on function public.dpp_api_supplier_invitation_accept(text) from public,anon;
revoke all on function public.dpp_api_supplier_invitations_list(uuid) from public,anon;

grant execute on function public.dpp_api_supplier_invitation_create(uuid,text,text,text,timestamptz) to authenticated;
grant execute on function public.dpp_api_supplier_invitation_accept(text) to authenticated;
grant execute on function public.dpp_api_supplier_invitations_list(uuid) to authenticated;

comment on function public.dpp_api_supplier_invitation_accept(text) is
  'BAT52: token-holder acceptance creates only supplier-scoped portal membership, never organization membership.';
